packages/gpio_pkg.sv
includes/axi4l_defines.svh
includes/gpio_defines.svh
structure/interfaces/axi4l_interface.sv
structure/interfaces/gpio_interface.sv
rtl/top.sv
+incdir+./includes/
+incdir+./configurations/
+incdir+./behaviour/sequence_items/
+incdir+./behaviour/sequences/
+incdir+./structure/register_layer/
+incdir+./structure/sequencers/
+incdir+./structure/drivers/
+incdir+./structure/monitors/
+incdir+./structure/agents/
+incdir+./structure/environments/
+incdir+./behaviour/tests/
