packages/gpio_pkg.sv
structure/interfaces/axi4l_interface.sv
structure/interfaces/gpio_interface.sv
rtl/gpio_defs.v
rtl/gpio.v
rtl/top.sv
+incdir+./configurations/
+incdir+./behaviour/sequence_items/
+incdir+./structure/sequencers/
