packages/gpio_pkg.sv
structure/interfaces/axi4l_interface.sv
structure/interfaces/gpio_interface.sv
rtl/gpio_new.v
rtl/top.sv
+incdir+./includes/
+incdir+./configurations/
+incdir+./behaviour/sequence_items/
+incdir+./behaviour/sequences/
+incdir+./behaviour/sequences/virtual_sequences/
+incdir+./structure/register_layer/
+incdir+./structure/drivers/
+incdir+./structure/monitors/
+incdir+./structure/agents/
+incdir+./structure/environments/
+incdir+./behaviour/tests/
